# Generated by Django 5.1.7 on 2025-03-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meaningvalue',
            unique_together=set(),
        ),
    ]
