# Generated by Django 5.1.7 on 2025-03-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot_cards.spread')),
            ],
            options={
                'unique_together': {('spread', 'name')},
            },
        ),
    ]
