# Generated by Django 5.1.7 on 2025-03-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0002_spread_spreadposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spreadposition',
            old_name='x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='spreadposition',
            old_name='y',
            new_name='top',
        ),
    ]
