# Generated by Django 5.1.7 on 2025-03-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_cards', '0004_spreadposition_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spreadposition',
            options={'ordering': ['position']},
        ),
    ]
